"""
Extra configs to be added to doc/source/conf.py (generated by sphinx-quickstart)

Add the following lines at the end of ``conf.py``:

from conf_extra import add_global
add_global(globals(), theme='stanford', extra_css=[])
"""
import os
import sys

global_keys_before = set(globals().keys())

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

mathjax_path = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

# Napoleon settings
# http://www.sphinx-doc.org/en/1.5.1/ext/napoleon.html#configuration
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# collect newly added globals to pass to conf.py
global_keys_added = set(globals().keys()) - global_keys_before

def get_html_configs(theme):
    """
    The theme to use for HTML and HTML Help pages.  
    http://www.sphinx-doc.org/en/1.5.1/theming.html
    
    Theme options are theme-specific and customize the look and feel of a theme
    further.  For a list of options available for each theme, see the
    documentation.
    http://www.sphinx-doc.org/en/1.5.1/config.html#confval-html_theme_options
    html_theme_options = { "rightsidebar": "true", "relbarbgcolor": "black" }
    """
    theme = theme.replace('-', '_')
    if theme == 'sphinx_rtd':
        import sphinx_rtd_theme
        return dict(html_theme = "sphinx_rtd_theme",
                    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()])
    elif theme == 'stanford':
        import stanford_theme
        return dict(html_theme = "stanford_theme",
                    html_theme_path = [stanford_theme.get_html_theme_path()])
    else:
        return dict(html_theme = "classic")


def get_extra_css(extra_css):
    def setup(app):
        "Defining setup(app) forces the script to load css"
        if extra_css:
            app.add_stylesheet(extra_css)
    return dict(setup=setup)


def add_global(global_dict, theme='stanford', extra_css=''):
    """
    Args:
      global_dict: ``globals()`` from conf.py
    """
    for k in global_keys_added:
        if k in global_dict:
            print('CONF_EXTRA: overriding', k)
        global_dict[k] = globals()[k]
    global_dict.update(get_html_configs(theme))
    global_dict.update(get_extra_css(extra_css))
